language: java
jdk:
  - openjdk8
install: echo "skiping install phase"
env:
  - IDEA_VERSION=2019.2.1 SCALA_PLUGIN_VERSION=2019.2.20 ENABLE_IDEA_GROOVY_PLUGIN=true ENABLE_IDEA_SCALA_PLUGIN=true
  - IDEA_VERSION=2019.2.1 SCALA_PLUGIN_VERSION=2019.2.20 ENABLE_IDEA_GROOVY_PLUGIN=false ENABLE_IDEA_SCALA_PLUGIN=false
  - IDEA_VERSION=2019.1 SCALA_PLUGIN_VERSION=2019.1.6 ENABLE_IDEA_GROOVY_PLUGIN=true ENABLE_IDEA_SCALA_PLUGIN=true
  - IDEA_VERSION=2019.1 SCALA_PLUGIN_VERSION=2019.1.6 ENABLE_IDEA_GROOVY_PLUGIN=true ENABLE_IDEA_SCALA_PLUGIN=false
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT SCALA_PLUGIN_VERSION=2019.3.19 ENABLE_IDEA_GROOVY_PLUGIN=true ENABLE_IDEA_SCALA_PLUGIN=true
#  - IDEA_VERSION=LATEST-EAP-SNAPSHOT SCALA_PLUGIN_VERSION=2019.3.19 ENABLE_IDEA_GROOVY_PLUGIN=true ENABLE_IDEA_SCALA_PLUGIN=false
matrix:
  allow_failures:
    - env: IDEA_VERSION=2019.1 SCALA_PLUGIN_VERSION=2019.1.6 ENABLE_IDEA_GROOVY_PLUGIN=true ENABLE_IDEA_SCALA_PLUGIN=true
    - env: IDEA_VERSION=LATEST-EAP-SNAPSHOT SCALA_PLUGIN_VERSION=2019.3.19 ENABLE_IDEA_GROOVY_PLUGIN=true ENABLE_IDEA_SCALA_PLUGIN=true
#    - env: IDEA_VERSION=LATEST-EAP-SNAPSHOT SCALA_PLUGIN_VERSION=2019.3.19 ENABLE_IDEA_GROOVY_PLUGIN=true ENABLE_IDEA_SCALA_PLUGIN=false
  fast_finish: true
script:
 - ./gradlew check -PideaVersion=$IDEA_VERSION -PscalaPluginVersion=$SCALA_PLUGIN_VERSION -PenableIdeaGroovyPlugin=$ENABLE_IDEA_GROOVY_PLUGIN -PenableIdeaScalaPlugin=$ENABLE_IDEA_SCALA_PLUGIN jacocoRootReport
after_failure: ./print_surefire_reports.sh
after_success:
  - ./gradlew coveralls
#  - ./gradlew cobertura coveralls
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
